package springMVC.mapper;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import springMVC.dto.UserDto;

public interface UserDtoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_t
     *
     * @mbggenerated Wed Sep 04 11:01:58 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_t
     *
     * @mbggenerated Wed Sep 04 11:01:58 CST 2019
     */
    int insert(UserDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_t
     *
     * @mbggenerated Wed Sep 04 11:01:58 CST 2019
     */
    int insertSelective(UserDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_t
     *
     * @mbggenerated Wed Sep 04 11:01:58 CST 2019
     */
    UserDto selectByPrimaryKey(Integer id);
    
    /**
     * @author FuqCalendar
     * @date 2019年9月4日15:11:08
     * @param suer
     * @return
     */
    List<Map<String,Object>> selectByUser (@Param("user") String user);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_t
     *
     * @mbggenerated Wed Sep 04 11:01:58 CST 2019
     */
    int updateByPrimaryKeySelective(UserDto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_t
     *
     * @mbggenerated Wed Sep 04 11:01:58 CST 2019
     */
    int updateByPrimaryKey(UserDto record);
}